import {
  TrendingUp,
  Shield,
  Globe,
  Bot,
  Lock,
  Star,
} from "lucide-react";

export const plans = [
  {
    id: 1,
    sectionid: "starter",
    name: "Starter Plan",
    emoji: "🌱",
    icon: Shield,
    tagline: "Perfect for Beginners",
    minInvestment: 100,
    expectedReturn: "5–8%",
    duration: "30 days",
    renewable: true,
    riskLevel: "Low",
    gradient: "from-green-400 to-emerald-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    features: [
      "Capital protected (limited risk exposure)",
      "Automated portfolio rebalancing",
      "Weekly performance reports",
      "Early withdrawal available with small fee",
    ],
    targetAudience: "Beginners, students, or cautious investors",
    popular: false,
  },
  {
    id: 2,
    sectionid: "growth",
    name: "Growth Plan",
    emoji: "🚀",
    icon: TrendingUp,
    tagline: "Scale Your Portfolio",
    minInvestment: 500,
    expectedReturn: "10–15%",
    duration: "90 days",
    renewable: false,
    riskLevel: "Medium",
    gradient: "from-blue-400 to-indigo-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    features: [
      "Diversified portfolio (crypto, ETFs, commodities)",
      "Performance bonuses for consistent deposits",
      "Risk management tools included",
      "Free 1-on-1 consultation per month",
    ],
    targetAudience: "Intermediate investors looking for long-term growth",
    popular: true,
  },
  {
    id: 3,
    sectionid: "premium",
    name: "Premium Plan",
    emoji: "💼",
    icon: Star,
    tagline: "Elite Investment Experience",
    minInvestment: 5000,
    expectedReturn: "20–25%",
    duration: "180 days",
    renewable: false,
    riskLevel: "Medium-High",
    gradient: "from-purple-400 to-violet-600",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    features: [
      "Dedicated financial advisor",
      "Real-time analytics dashboard",
      "Access to private investment opportunities",
      "Monthly investor report and quarterly audit",
    ],
    targetAudience: "High-net-worth individuals or professionals",
    popular: false,
  },
  {
    id: 4,
    sectionid: "impact",
    name: "Impact Plan",
    emoji: "🌍",
    icon: Globe,
    tagline: "Invest for Good",
    minInvestment: 250,
    expectedReturn: "6–10%",
    duration: "60 days",
    renewable: true,
    riskLevel: "Low-Medium",
    gradient: "from-teal-400 to-cyan-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    features: [
      "Green energy, tech for good, clean water projects",
      "Transparent project updates",
      "Certified impact investment partners",
      "Reinvest profits into ethical portfolios",
    ],
    targetAudience: "Socially-conscious investors",
    popular: false,
  },
  {
    id: 5,
    sectionid: "protrader",
    name: "Pro Trader Plan",
    emoji: "📈",
    icon: Bot,
    tagline: "AI-Powered Trading",
    minInvestment: 1000,
    expectedReturn: "25–40%",
    duration: "30–60 days",
    renewable: true,
    riskLevel: "High",
    gradient: "from-orange-400 to-red-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    features: [
      "AI-powered trading bots",
      "High-frequency trading strategies",
      "Stop-loss and exit strategy customization",
      "Daily performance tracking",
    ],
    targetAudience: "Risk-tolerant investors and active traders",
    popular: false,
  },
  {
    id: 6,
    sectionid: "fixedreturn",
    name: "Fixed Return Plan",
    emoji: "🔐",
    icon: Lock,
    tagline: "Guaranteed Stability",
    minInvestment: 300,
    expectedReturn: "8%",
    duration: "3 months",
    renewable: false,
    riskLevel: "Very Low",
    gradient: "from-gray-400 to-slate-600",
    bgColor: "bg-gray-50",
    borderColor: "border-gray-200",
    features: [
      "Fixed interest payout (guaranteed)",
      "No market exposure",
      "Insurance-backed capital guarantee",
      "Predictable income without volatility",
    ],
    targetAudience: "Conservative investors who want stability",
    popular: false,
  },
];