import {
  TrendingUp,
  Shield,
  Globe,
  Bot,
  Lock,
  Star,
} from "lucide-react";

export const plans = [
  {
    id: 1,
    sectionid: "starter",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    duration: "30 days",
    emoji: "🌱",
    expectedReturn: "15%",
    features: [
      "Capital protected (limited risk exposure)",
      "Automated portfolio rebalancing",
      "Weekly performance reports",
      "Early withdrawal available with small fee",
    ],
    gradient: "from-green-400 to-emerald-600",
    icon: Shield,
    minInvestment: 100,
    name: "Starter Plan",
    popular: false,
    renewable: true,
    riskLevel: "Low",
    tagline: "Perfect for Beginners",
    targetAudience: "Beginners, students, or cautious investors",
  },
  {
    id: 2,
    sectionid: "growth",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    duration: "90 days",
    emoji: "🚀",
    expectedReturn: "17.5%",
    features: [
      "Diversified portfolio (crypto, ETFs, commodities)",
      "Performance bonuses for consistent deposits",
      "Risk management tools included",
      "Free 1-on-1 consultation per month",
    ],
    gradient: "from-blue-400 to-indigo-600",
    icon: TrendingUp,
    minInvestment: 500,
    name: "Growth Plan",
    popular: true,
    renewable: true,
    riskLevel: "Medium",
    tagline: "Scale Your Portfolio",
    targetAudience: "Intermediate investors looking for long-term growth",
  },
  {
    id: 3,
    sectionid: "premium",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    duration: "180 days",
    emoji: "💼",
    expectedReturn: "20%",
    features: [
      "Dedicated financial advisor",
      "Real-time analytics dashboard",
      "Access to private investment opportunities",
      "Monthly investor report and quarterly audit",
    ],
    gradient: "from-purple-400 to-violet-600",
    icon: Star,
    minInvestment: 2000,
    name: "Premium Plan",
    popular: false,
    renewable: true,
    riskLevel: "Medium-High",
    tagline: "Elite Investment Experience",
    targetAudience: "High-net-worth individuals or professionals",
  },
  {
    id: 4,
    sectionid: "elite",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    duration: "365 days",
    emoji: "🌍",
    expectedReturn: "22.5%",
    features: [
      "Green energy, tech for good, clean water projects",
      "Transparent project updates",
      "Certified elite investment partners",
      "Reinvest profits into ethical portfolios",
    ],
    gradient: "from-teal-400 to-cyan-600",
    icon: Globe,
    minInvestment: 10000,
    name: "Elite Plan",
    popular: false,
    renewable: true,
    riskLevel: "High",
    tagline: "Invest for Good",
    targetAudience: "Socially-conscious investors",
  },
  // {
  //   id: 5,
  //   sectionid: "protrader",
  //   name: "Pro Trader Plan",
  //   emoji: "📈",
  //   icon: Bot,
  //   tagline: "AI-Powered Trading",
  //   minInvestment: 1000,
  //   expectedReturn: "25–40%",
  //   duration: "30–60 days",
  //   renewable: true,
  //   riskLevel: "High",
  //   gradient: "from-orange-400 to-red-600",
  //   bgColor: "bg-orange-50",
  //   borderColor: "border-orange-200",
  //   features: [
  //     "AI-powered trading bots",
  //     "High-frequency trading strategies",
  //     "Stop-loss and exit strategy customization",
  //     "Daily performance tracking",
  //   ],
  //   targetAudience: "Risk-tolerant investors and active traders",
  //   popular: false,
  // },
  // {
  //   id: 6,
  //   sectionid: "fixedreturn",
  //   name: "Fixed Return Plan",
  //   emoji: "🔐",
  //   icon: Lock,
  //   tagline: "Guaranteed Stability",
  //   minInvestment: 300,
  //   expectedReturn: "8%",
  //   duration: "3 months",
  //   renewable: false,
  //   riskLevel: "Very Low",
  //   gradient: "from-gray-400 to-slate-600",
  //   bgColor: "bg-gray-50",
  //   borderColor: "border-gray-200",
  //   features: [
  //     "Fixed interest payout (guaranteed)",
  //     "No market exposure",
  //     "Insurance-backed capital guarantee",
  //     "Predictable income without volatility",
  //   ],
  //   targetAudience: "Conservative investors who want stability",
  //   popular: false,
  // },
];