export const testimonials = [
  {
    id: 1,
    quote: "TrustFx didn't just grow my portfolio — it grew my confidence in investing.",
    content:
      "I started with just $200 and a lot of skepticism. But within months, I saw real returns and even better communication. Their updates, guidance, and dashboard made me feel in control the whole time. This isn't just another trading app — it's a platform that actually cares.",
    name: "Jared K.",
    location: "Atlanta, GA",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
    investment: "$200",
    returns: "127%",
  },
  {
    id: 2,
    quote: "Finally, an investment platform that doesn't treat you like just another number.",
    content:
      "From the moment I joined TrustFx, I felt seen. The interface is user-friendly, the returns are realistic, and the transparency is unlike anything I've experienced. Their team is responsive, and every decision feels intentional.",
    name: "Nina M.",
    location: "London, UK",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
    investment: "$1,500",
    returns: "89%",
  },
  {
    id: 3,
    quote: "What stood out most? Trust.",
    content:
      "There are thousands of platforms promising profits. TrustFx actually delivers — with accountability, smart insights, and real-time results. I've recommended it to my friends, family, and even my accountant.",
    name: "Tosin A.",
    location: "Lagos, Nigeria",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
    investment: "$800",
    returns: "156%",
  },
  {
    id: 4,
    quote: "From confused to confident.",
    content:
      "I knew nothing about investing when I signed up. Now I'm managing my own plans, understanding market movements, and even teaching my daughter. TrustFx made me believe I could do this.",
    name: "Laura T.",
    location: "Cape Town, South Africa",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
    investment: "$350",
    returns: "94%",
  },
  {
    id: 5,
    quote: "One word: seamless.",
    content: "Deposit. Invest. Track. Withdraw. Everything works perfectly — and the returns speak for themselves.",
    name: "Michael D.",
    location: "Toronto, Canada",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
    investment: "$2,200",
    returns: "112%",
  },
  {
    id: 6,
    quote: "My experience with TrustFx has been nothing short of phenomenal.",
    content:
      "I've been investing for over a decade and have never felt more informed or supported. Their team provides data-backed recommendations, and the app itself is intuitive and elegant. But what truly sets them apart is their ethics. They don't overpromise — they overdeliver.",
    name: "Chloe S.",
    location: "New York, NY",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
    investment: "$5,000",
    returns: "143%",
  },
  {
    id: 7,
    quote: "I'm not just making money — I'm building something.",
    content:
      "Every dollar I've invested with TrustFx feels intentional. This is the kind of long-term platform that helps you plan for retirement, your kids, or just financial peace. I'm not gambling here — I'm growing.",
    name: "Omar R.",
    location: "Dubai, UAE",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
    investment: "$3,800",
    returns: "178%",
  },
  {
    id: 8,
    quote: "Security was my biggest concern — and they nailed it.",
    content:
      "Encrypted transactions, two-factor authentication, SIPC insurance, and a crystal-clear history of every move. I sleep well knowing my money's in good hands.",
    name: "Samantha J.",
    location: "Dublin, Ireland",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
    investment: "$1,200",
    returns: "98%",
  },
]